## 1. Rename axis

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html#pandas.DataFrame.rename
`DataFrame.rename(mapper=None, *, index=None, columns=None, axis=None, copy=None, inplace=False, level=None, errors='ignore')`

+ mapper: dict-like or function. Dict-like or function transformations to apply to that axisâ€™ values. Use either mapper and axis to specify the axis to target with mapper, or index and columns.

In [16]:
import pandas as pd
titanic = pd.read_csv("data/titanic.csv")
houses = pd.read_csv("data/kc_house_data.csv")
netflix = pd.read_csv("data/netflix_titles.csv",sep = "|", index_col = 0)
btc = pd.read_csv("data/coin_Bitcoin.csv")
countries = pd.read_csv("data/world-happiness-report-2021.csv").set_index("Country name")

In [17]:
countries.head()

,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
Country name,,,,,,,,,,,,,,,,,,,
Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.0,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253
Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.7,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868
Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.4,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839
Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.0,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967
Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.4,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798

In [18]:
replace = {"Regional indicator": "Regional Indicator"}
countries.rename(columns = replace).head()

,Regional Indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
Country name,,,,,,,,,,,,,,,,,,,
Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.0,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253
Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.7,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868
Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.4,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839
Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.0,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967
Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.4,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798

In [35]:
change = {"France":"FR"}
countries.rename(index = change, inplace = True)
countries.sort_values("Country name")

,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
Country name,,,,,,,,,,,,,,,,,,,
Afghanistan,South Asia,2.523,0.038,2.596,2.449,7.695,0.463,52.493,0.382,-0.102,0.924,2.43,0.370,0.000,0.126,0.000,0.122,0.010,1.895
Albania,Central and Eastern Europe,5.117,0.059,5.234,5.001,9.520,0.697,68.999,0.785,-0.030,0.901,2.43,1.008,0.529,0.646,0.491,0.168,0.024,2.250
Algeria,Middle East and North Africa,4.887,0.053,4.991,4.783,9.342,0.802,66.005,0.480,-0.067,0.752,2.43,0.946,0.765,0.552,0.119,0.144,0.120,2.242
Argentina,Latin America and Caribbean,5.929,0.056,6.040,5.819,9.962,0.898,69.000,0.828,-0.182,0.834,2.43,1.162,0.980,0.646,0.544,0.069,0.067,2.461
Armenia,Commonwealth of Independent States,5.283,0.058,5.397,5.168,9.487,0.799,67.055,0.825,-0.168,0.629,2.43,0.996,0.758,0.585,0.540,0.079,0.198,2.127
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela,Latin America and Caribbean,4.892,0.064,5.017,4.767,9.073,0.861,66.700,0.615,-0.169,0.827,2.43,0.852,0.897,0.574,0.284,0.078,0.072,2.135
Vietnam,Southeast Asia,5.411,0.039,5.488,5.334,8.973,0.850,68.034,0.940,-0.098,0.796,2.43,0.817,0.873,0.616,0.679,0.124,0.091,2.211
Yemen,Middle East and North Africa,3.658,0.070,3.794,3.521,7.578,0.832,57.122,0.602,-0.147,0.800,2.43,0.329,0.831,0.272,0.268,0.092,0.089,1.776
Zambia,Sub-Saharan Africa,4.073,0.069,4.209,3.938,8.145,0.708,55.809,0.782,0.061,0.823,2.43,0.528,0.552,0.231,0.487,0.227,0.074,1.975
Zimbabwe,Sub-Saharan Africa,3.145,0.058,3.259,3.030,7.943,0.750,56.201,0.677,-0.047,0.821,2.43,0.457,0.649,0.243,0.359,0.157,0.075,1.205

## 2. Replace

In [22]:
titanic["sex"].replace("female", "Woman")

0       Woman
1        male
2       Woman
3        male
4       Woman
        ...
1304    Woman
1305    Woman
1306     male
1307     male
1308     male
Name: sex, Length: 1309, dtype: object

When replace item with none, you must use `[None]`.

In [23]:
titanic["age"].replace(["?"], [None])

0           29
1       0.9167
2            2
3           30
4           25
         ...
1304      14.5
1305      None
1306      26.5
1307        27
1308        29
Name: age, Length: 1309, dtype: object

## 3. update values with `loc[]`

In [37]:
countries.loc["FR"]

Regional indicator                            Western Europe
Ladder score                                            6.69
Standard error of ladder score                         0.037
upperwhisker                                           6.762
lowerwhisker                                           6.618
Logged GDP per capita                                 10.704
Social support                                         0.942
Healthy life expectancy                                 74.0
Freedom to make life choices                           0.822
Generosity                                            -0.147
Perceptions of corruption                              0.571
Ladder score in Dystopia                                2.43
Explained by: Log GDP per capita                       1.421
Explained by: Social support                           1.081
Explained by: Healthy life expectancy                  0.804
Explained by: Freedom to make life choices             0.536
Explained by: Generosity                               0.092
Explained by: Perceptions of corruption                0.235
Dystopia + residual                                    2.521
Name: FR, dtype: object

In [38]:
countries.loc[["China","United States"],["upperwhisker","lowerwhisker"]]

               upperwhisker  lowerwhisker
Country name
China                 5.397         5.281
United States         7.047         6.856

In [48]:
countries.loc[["Finland", "Denmark"],["Regional indicator"]] = "Scandinavia"
countries.head()

,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual,Rigional indicator
Country name,,,,,,,,,,,,,,,,,,,,
Finland,Scandinavia,7.842,0.032,7.904,7.780,10.775,0.954,72.0,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253,Scandinavia
Denmark,Scandinavia,7.620,0.035,7.687,7.552,10.933,0.954,72.7,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868,Scandinavia
Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.4,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839,NaN
Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.0,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967,NaN
Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.4,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798,NaN

In [49]:
countries.loc[["Finland", "Denmark"],["Regional indicator","Weather" ]] = ["Scandinavia", "Cold"]

In [50]:
countries

,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,...,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual,Rigional indicator,Weather
Country name,,,,,,,,,,,,,,,,,,,,,
Finland,Scandinavia,7.842,0.032,7.904,7.780,10.775,0.954,72.000,0.949,-0.098,...,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253,Scandinavia,Cold
Denmark,Scandinavia,7.620,0.035,7.687,7.552,10.933,0.954,72.700,0.946,0.030,...,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868,Scandinavia,Cold
Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.400,0.919,0.025,...,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839,NaN,NaN
Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.000,0.955,0.160,...,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967,NaN,NaN
Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.400,0.913,0.175,...,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Lesotho,Sub-Saharan Africa,3.512,0.120,3.748,3.276,7.926,0.787,48.700,0.715,-0.131,...,2.43,0.451,0.731,0.007,0.405,0.103,0.015,1.800,NaN,NaN
Botswana,Sub-Saharan Africa,3.467,0.074,3.611,3.322,9.782,0.784,59.269,0.824,-0.246,...,2.43,1.099,0.724,0.340,0.539,0.027,0.088,0.648,NaN,NaN
Rwanda,Sub-Saharan Africa,3.415,0.068,3.548,3.282,7.676,0.552,61.400,0.897,0.061,...,2.43,0.364,0.202,0.407,0.627,0.227,0.493,1.095,NaN,NaN
Zimbabwe,Sub-Saharan Africa,3.145,0.058,3.259,3.030,7.943,0.750,56.201,0.677,-0.047,...,2.43,0.457,0.649,0.243,0.359,0.157,0.075,1.205,NaN,NaN
Afghanistan,South Asia,2.523,0.038,2.596,2.449,7.695,0.463,52.493,0.382,-0.102,...,2.43,0.370,0.000,0.126,0.000,0.122,0.010,1.895,NaN,NaN

## 4. make updates with `loc[]` and boolean masks

In [51]:
many_bedrooms = houses["bedrooms"] >= 10
many_bedrooms

0        False
1        False
2        False
3        False
4        False
         ...
21608    False
21609    False
21610    False
21611    False
21612    False
Name: bedrooms, Length: 21613, dtype: bool

In [53]:
houses.loc[many_bedrooms, ["price", "sqft_living"]]

           price  sqft_living
8757    520000.0         3000
13314  1148000.0         4590
15161   650000.0         3610
15870   640000.0         1620
19254   660000.0         2920

In [54]:
houses.loc[many_bedrooms, ["bedrooms"]] = "Greater than 9"

In [56]:
houses[many_bedrooms]

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
8757,1773100755,20140821T000000,520000.0,Greater than 9,3.00,3000,4960,2.0,0,0,...,7,2400,600,1918,1999,98106,47.5560,-122.363,1420,4960
13314,627300145,20140814T000000,1148000.0,Greater than 9,5.25,4590,10920,1.0,0,2,...,9,2500,2090,2008,0,98004,47.5861,-122.113,2730,10400
15161,5566100170,20141029T000000,650000.0,Greater than 9,2.00,3610,11914,2.0,0,0,...,7,3010,600,1958,0,98006,47.5705,-122.175,2040,11914
15870,2402100895,20140625T000000,640000.0,Greater than 9,1.75,1620,6000,1.0,0,0,...,7,1040,580,1947,0,98103,47.6878,-122.331,1330,4700
19254,8812401450,20141229T000000,660000.0,Greater than 9,3.00,2920,3745,2.0,0,0,...,7,1860,1060,1913,0,98105,47.6635,-122.320,1810,3745

We can access label through rows.